version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_rag
    restart: unless-stopped
    ports:
      - "6401:6333"  # HTTP API auf Host 6401 (Fallback-HTTP-Port)
      - "6402:6334"  # gRPC auf Host 6402
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - ./data/qdrant:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 10s
      timeout: 5s
      retries: 10