name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev/requirements.txt ]; then pip install -r dev/requirements.txt; fi
          pip install ruff black isort pytest pytest-cov coverage

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check .

      - name: Format (black --check)
        run: |
          black --version
          black --check .

      - name: Imports (isort --check-only)
        run: |
          isort --version
          isort --check-only .

      - name: Pytest
        env:
          # Tests ohne externe LLM-/Netzwerk-Abhängigkeiten ausführen
          DISABLE_GRPC: "true"
          MOCK_MODE: "true"
          OPENAI_API_KEY: ""
          QDRANT_URL: "http://localhost"
          QDRANT_PORT: "6333"
          QDRANT_AUTODETECT: "false"
          QDRANT_AUTOCREATE: "false"
          CANARY_PERCENT: "0"
          FEATURE_FLAG_USE_V2: "false"
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=backend_app --cov=backend_app_v2 --cov-report=xml --cov-fail-under=80